source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'sqlite3'
gem 'paperclip', '2.3.8'
gem 'menu_builder', '0.4.0'
gem 'RedCloth', '4.2.7'
gem 'devise'
gem 'reverse_captcha', '0.0.1'
gem 'will_paginate', '3.0.pre2'